import { ThemeProvider } from "@/components/providers/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { League_Spartan, Silkscreen } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const silkScreen = Silkscreen({
  subsets: ["latin"],
  weight: "400"
});

const leagueSpartan = League_Spartan({
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export const metadata: Metadata = {
//   title: "AI Chat Assistant",
//   description: "Chat with an AI assistant powered by OpenAI",
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className="antialiased">
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            {children}  {/* No sidebar here */}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
